### ISSUE TITLE
Per storyboard view controller enums may be useful

### ISSUE THREAD

**Issue by jshier** [NathanE73/Blackboard#3]
It will likely be useful if, for each storyboard, an enum was generated that contained each of the view controller identifiers, similar to the enums for the table view and collection view cells. At the very least it would allow stronger typing for the various `initializeFromStoryboard` methods.

**Comment by NathanE73** [comment]
This could be done, but I'm not sure of its value.  On the benefits lost will be the casting of the returned class.  Also a switch statement will require you to exhaust all options.

**Comment by jshier** [comment]
This would just be for the identifiers, similar to how the cell identifiers are treated. So instead of instantiating from the storyboard using the identifier directly, it would use the `rawValue` of the generated case.

**Comment by NathanE73** [comment]
With the latest enhancements to add support for prepare segue and should perform segue, I'm closing this as it isn't as necessary as previously.
